export const frameworks = {
  "next-app-js": {
    name: "Next.js (App Router + JavaScript)",
    templatePath: "templates/nextjs-app-js",
    scripts: {
      dev: "next dev --turbopack",
      build: "next build",
      start: "next start",
      lint: "next lint",
    },
    dependencies: {
      next: "latest",
      react: "latest",
      "react-dom": "latest",
      xtrixui: "latest",
    },
    devDependencies: {
      tailwindcss: "latest",
      postcss: "latest",
      eslint: "latest",
      "eslint-config-next": "latest",
    },
  },
  "next-app-ts": {
    name: "Next.js (App Router + TypeScript)",
    templatePath: "templates/nextjs-app-ts",
    scripts: {
      dev: "next dev --turbopack",
      build: "next build",
      start: "next start",
      lint: "next lint",
    },
    dependencies: {
      next: "latest",
      react: "latest",
      "react-dom": "latest",
      xtrixui: "latest",
    },
    devDependencies: {
      tailwindcss: "latest",
      typescript: "latest",
      "@types/node": "latest",
      "@types/react": "latest",
      "@types/react-dom": "latest",
      postcss: "latest",
      eslint: "latest",
      "eslint-config-next": "latest",
    },
  },
  "vite-react": {
    name: "Vite (React + SWC + JavaScript)",
    templatePath: "templates/vite-react",
    scripts: {
      dev: "vite",
      build: "vite build",
      lint: "eslint .",
      preview: "vite preview",
    },
    dependencies: {
      react: "latest",
      "react-dom": "latest",
      xtrixui: "latest",
    },
    devDependencies: {
      "@eslint/js": "latest",
      "@types/react": "latest",
      "@types/react-dom": "latest",
      "@vitejs/plugin-react-swc": "latest",
      autoprefixer: "latest",
      eslint: "latest",
      "eslint-plugin-react": "latest",
      "eslint-plugin-react-hooks": "latest",
      "eslint-plugin-react-refresh": "latest",
      globals: "latest",
      postcss: "latest",
      tailwindcss: "latest",
      vite: "latest",
    },
  },
  "vite-react-ts": {
    name: "Vite (React + SWC + TypeScript)",
    templatePath: "templates/vite-react-ts",
    scripts: {
      dev: "vite",
      build: "tsc -b && vite build",
      lint: "eslint .",
      preview: "vite preview",
    },
    dependencies: {
      react: "latest",
      "react-dom": "latest",
      xtrixui: "latest",
    },
    devDependencies: {
      "@eslint/js": "latest",
      "@types/react": "latest",
      "@types/react-dom": "latest",
      "@vitejs/plugin-react-swc": "latest",
      autoprefixer: "latest",
      eslint: "latest",
      "eslint-plugin-react-hooks": "latest",
      "eslint-plugin-react-refresh": "latest",
      globals: "latest",
      postcss: "latest",
      tailwindcss: "latest",
      typescript: "latest",
      "typescript-eslint": "latest",
      vite: "latest",
    },
  },
  // Add more frameworks
};
